### ISSUE TITLE
TF activities in single-cell: `run_ulm` takes too long

### ISSUE THREAD

**Issue by nicholaslimwy** [saezlab/decoupleR#106]
Thank you for developing this package! Unfortunately I've been struggling to construct the univariate linear model with the run_ulm function on my dataset. I assume this is due to the large cell numbers I have (~35k) which failed after 8 hours, but despite downsampling it to 1k cells, the function is still taking just as long. I've seen that an alternative solution is to run the datset using Python, but was wondering if constructing the CollecTRI database, followed by running it on VIPER would be a viable alternative?

**Comment by PauBadiaM** [comment]
Hi @nicholaslimwy,

May I ask which version of decoupleR are you running? It could be that you are using an older version that is less efficient than the current one. I would try to install it from GitHub and try again:
```R
remotes::install_github('saezlab/decoupleR')
```

Else yes, the alternative is to switch to python which should take seconds to run on a normal laptop.
VIPER, although we saw in our benchmark that it has less predictive performance than ULM, is also a valid alternative, although it can also be slow when its pleiotropy argument is used, for faster (but less accurate) results you can set it to `FALSE`.

Hope this is helpful!

**Comment by nicholaslimwy** [comment]
I was running 2.6.0 and have since updated it! I'll make the switch over to Python if it's not efficient enough. Thank you for your help!
