### ISSUE TITLE
get_collectri is hard coded for human

### ISSUE THREAD

**Issue by karJac** [saezlab/decoupleR#109]
Hi, 

After installing the decoupleR package from Bioconductor on R version 4.3.2, I encountered an issue with the function decoupleR::get_collectri(). Although the function's description suggests that it supports both human and mouse datasets, its implementation appears to be hardcoded exclusively for human data. 

![image](https://github.com/saezlab/decoupleR/assets/98103985/57e19ce5-b700-4e4d-ae64-b75a39dd3ed6)

We can see in the code that parameter "organism" is not being caleld inside OmnipathR::collectri(). The default parameter for "organism" in OmnipathR::collectri() is human, thus the function is hardcoded for "human".

![image](https://github.com/saezlab/decoupleR/assets/98103985/f1ac9fdb-d524-449f-b346-11e69ddecca1)

Here is the code of get_collectri function with correct calling of "organism" parameter:
```

get_collectri <- function(organism = "human", split_complexes = FALSE){
  if (organism == "human"){
    organism <- "9606"
  } else if (organism == "mouse"){
    organism <- "10090"
  } else {
    stop("Interactions are available only for human and mouse!")
  }
  
  collectri <- OmnipathR::collectri(organism=organism) #default organism is human
  cols <- c("source_genesymbol", "target_genesymbol", "is_stimulation", 
            "is_inhibition")
  collectri_interactions <- collectri[!stringr::str_detect(collectri$source, 
                                                           "COMPLEX"), cols]
  collectri_complex <- collectri[stringr::str_detect(collectri$source, 
                                                     "COMPLEX"), cols]
  if (!split_complexes) {
    collectri_complex <- collectri_complex %>% dplyr::mutate(source_genesymbol = dplyr::case_when(stringr::str_detect(source_genesymbol, 
                                      "JUN") | stringr::str_detect(source_genesymbol, "FOS") ~ 
                    "AP1", stringr::str_detect(source_genesymbol, "REL") | 
                    stringr::str_detect(source_genesymbol, "NFKB") ~ 
                    "NFKB"))
  }
  collectri <- base::rbind(collectri_interactions, collectri_complex) %>% 
    dplyr::distinct(.data$source_genesymbol, .data$target_genesymbol, 
                    .keep_all = TRUE) %>% dplyr::mutate(weight = dplyr::case_when(is_stimulation == 
                         1 ~ 1, is_stimulation == 0 ~ -1)) %>% dplyr::select(.data$source_genesymbol, 
                                    .data$target_genesymbol, .data$weight) %>% dplyr::rename(source = .data$source_genesymbol, 
                                          target = .data$target_genesymbol, mor = .data$weight, 
                                    )
  return(collectri)
}
```

 Now it seems to work properly.
![image](https://github.com/saezlab/decoupleR/assets/98103985/0ed8cef3-fa45-4252-9aba-49d5ad014110)
 
 

Hope that my post will be helpful for you and thank you for creating this package!
Karol

**Comment by deeenes** [comment]
Hi Karol,

This has been fixed [long time ago](https://github.com/saezlab/decoupleR/blob/2a57d2a93709001ca54f0a5701f413ce6b4fe3bb/R/utils-omnipath.R#L102), I recommend to update the package from this git repo:

```
library(remotes)
remotes::install_github('saezlab/decoupleR')
```

I'll check why the update is not included in the latest BioC release.

Best,

Denes

**Comment by karJac** [comment]
It seems that BiocManager::install("decoupleR") installed the version 2.6.0, instead of the latest 2.8.0, because BiocManager was outdated (3.16 instead of 3.18). My bad then, sorry for the confusion.
