### ISSUE TITLE
Question about TF activity inference analysis in single cell integrated datasets

### ISSUE THREAD

**Issue by ChrisTzaferis** [saezlab/decoupleR#111]
Hi, thank you for developing this very useful package! 
I would like to ask you for some clarifications regarding the TF activity inference on single cell datasets.

1) In case the single cell Seurat object contains more than one conditions after integration or batch correction analysis, is it correct to follow the vignette using the data slot of the RNA assay or it would be advisable to perform the analysis separately for each condition?

2) If it is correct to proceed with the analysis in the integrated object as described above, can the methodology described for the heatmap production (detecting the top deviant TFs) be utilized to compare activities between the clusters of the dataset, when they follow the format: cluster1_Healthy, cluster1_Disease, cluster2_Healthy, cluster2_Disease,...,etc?

Thank you for your time.

**Comment by PauBadiaM** [comment]
Hi @ChrisTzaferis,

If your aim is to compare conditions, I would rather perform differential expression analysis at the pseudobulk level, per cell type and then take the contrast statistics that you obtain (for example the `stat` column of DESeq2) as input for decoupleR. This way you would obtain which TFs are differentially changing the most for each cell type. Once you have the contrasts, you can follow the vignette for [bulk](https://saezlab.github.io/decoupleR/articles/tf_bk.html), else we have a [pseudobulk vignette](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html) but it is in python. Hope this is helpful!

**Comment by ChrisTzaferis** [comment]
Thank you for your suggestion, I will give it a try!
