### ISSUE TITLE
get_collectri is not able to fetch the right organism

### ISSUE THREAD

**Issue by tamerbio** [saezlab/decoupleR#115]
Dear @PauBadiaM ,
I tried to apply `get_collectri` on `mouse` bulk RNA-seq data however the function returned a human gene regulatory network ids.
which probably shows an error message in the downstream analysis and visualization.
could you please double-check this function on mouse gene IDs?
moreover, you mentioned in the vignette that the `rat` database is also available but I was not able to find it. 
thank you so much

best,
Tamer

**Comment by PauBadiaM** [comment]
Hi @tamerbio,

Could you install the latest version from GitHUb and try again:
```R
remotes::install_github('saezlab/decoupleR')
```
Let me know how it goes!

**Comment by tamerbio** [comment]
Hi @PauBadiaM,
thanks for your quick reply.
I tried already but still the same error.
`net <- get_collectri (organism = "mouse", split_complexes=FALSE)`
```
[2024-02-22 09:42:49] [SUCCESS] [OmnipathR] Downloaded 64495 interactions.
> net
# A tibble: 42,595 × 3
   source target   mor
   <chr>  <chr>  <dbl>
 1 MYC    TERT       1
 2 SPI1   BGLAP      1
 3 SMAD3  JUN        1
 4 SMAD4  JUN        1
```

```
contrast_acts <- run_wmean(mat= deg[, 'stat', drop=FALSE], net=net,
                           .source='source', .target='target',
                           .mor='mor', times = 100, minsize = 5)

```
```
Error in filt_minsize(rownames(mat), network, minsize) : 
  Network is empty after intersecting it with mat and
filtering it by sources with at least 5 targets. Make sure mat and 
network have shared target features or reduce the number assigned to minsize


```
thanks much
Tamer

**Comment by PauBadiaM** [comment]
Hi @tamerbio ,

Mhm strange, have you restarted your R session? This should work with the GitHub version:
```R
net <- get_collectri (organism = "mouse", split_complexes=FALSE)
net
```
```
# A tibble: 38,665 × 3
   source target   mor
   <chr>  <chr>  <dbl>
 1 Myc    Tert       1
 2 Spi1   Bglap2     1
 3 Spi1   Bglap      1
 4 Spi1   Bglap3     1
```

Can you print which `decoupleR` and `OmnipathR` version you have?

**Comment by tamerbio** [comment]
Thanks much @PauBadiaM,
it did work 

thanks a lot
Tamer

**Comment by tamerbio** [comment]
I wish you could include rat data for PROGENy function.
thanks again
Tamer

**Comment by PauBadiaM** [comment]
Hi @tamerbio,

You can retrieve it easily:
```R
net <- get_collectri(organism = "rat")
net
```
```
# A tibble: 24,372 × 3
   source target   mor
   <chr>  <chr>  <dbl>
 1 Myc    Tert       1
 2 Spi1   Bglap      1
 3 Smad3  Jun        1
 4 Smad4  Jun        1
```
