### ISSUE TITLE
scRNA TF activity inference 

### ISSUE THREAD

**Issue by SofyaMa** [saezlab/decoupleR#117]
Great idea to extend the package to sc-data. I am trying to apply it to may Seurat object, however the run_uml function does not terminate. At least not within 24 hours.... do you know what I could do to speed up the TF activity inference. I am following the standard tutorial , please find my code attached.. any help is appreciated :D 

```r
load("~/scRNA/data/merged_seurat.RData")
#PKN with TFs 
net <- get_collectri(organism='human', split_complexes=FALSE)
# Extract the normalized log-transformed counts
mat <- as.matrix(merged_seurat@assays$RNA@data)

# Run ulm
acts <- run_ulm(mat=mat, net=net, .source='source', .target='target',
                .mor='mor', minsize = 5)
acts

```

**Comment by SofyaMa** [comment]
or other question: can I somehow parallelize this function ?

**Comment by PauBadiaM** [comment]
Hi @SofyaMa,

It might be the case that you are running an old version of decoupleR. You could try installing the latest from GithHub:
```R
remotes::install_github('saezlab/decoupleR')
```
Or you could try the [python version](https://decoupler-py.readthedocs.io/en/latest/) of the package which is optimized to work with large sc atlases. Hope this is helpful!
