### ISSUE TITLE
Subscript out of bounds error

### ISSUE THREAD

**Issue by savagesr** [saezlab/decoupleR#130]
Hello,

I am trying to run decoupleR but have just encountered an error after updating to the most recent version today when using run_ulm or run_mlm:
```R
sample_acts <- run_ulm(mat=counts, net=net, .source='source', .target='target', .mor='mor', minsize = 5)
```
```
Error in mor_mat[[.target, .source]] <- .weight : 
  [[ ]] subscript out of bounds
```
I first encountered the error on my data but it also occurred for me when exactly following the tutorial on "Transcription factor activity inference in bulk RNA-seq". 

I am using OmnipathR version 3.13.5 and decoupleR 2.9.7.

**Comment by PauBadiaM** [comment]
Hi @savagesr,

Thanks for opening this issue. I've checked and this error is because of a new bug from `OmnipathR` that introduces `NA`s in the network when calling `get_collectri`. @deeenes, something went wrong with the new update and now all sources that come from a complex return `NA`s, could you have a look?

**Comment by Sigmatilde** [comment]
I encountered the same error, after removing the rows of net with NA the command `run_ulm` is working. thank you!

**Comment by PauBadiaM** [comment]
@deeenes any update on this issue? I've checked and it is only the R version of omnipath, the python version works fine.

**Comment by JenMcKey** [comment]
Hi! 
I'm encountering the same error, but removing NAs from net (using drop_na()) doesn't solve it for me. Any ideas what I can try? I'm also using OmnipathR 3.13.5 and decoupleR 2.9.7. 
Thank you!

**Comment by thekingofall** [comment]
thank you
net2 <- subset(net, !is.na(source) & !is.na(target))
acts <- run_ulm(mat=mat, net=net2, .source='source', .target='target',
                .mor='mor', minsize = 5)
                
it works

**Comment by JenMcKey** [comment]
Yes, that worked. Thank you so much @thekingofall!

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）

**Comment by PauBadiaM** [comment]
@deeenes any update on this error?

**Comment by PauBadiaM** [comment]
@deeenes has this been fixed?

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）

**Comment by PauBadiaM** [comment]
@deeenes any update?

**Comment by deeenes** [comment]
Hi all, apologies for the late reply!

With OmnipathR 3.13.8 this issue should be fixed. Please update from our git repo:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR')
```

Sorry in advance if anything else got broken, there are quite some updates in this release. If you see any error, ping me here and I'll fix it quickly.

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）
