### ISSUE TITLE
Error in do.call(stop, list(m), envir = env)

### ISSUE THREAD

**Issue by Megan0921** [saezlab/decoupleR#132]
Dear Team,
I'm trying to use decoupleR to retrieve CollecTRI from OmniPath and have encountered an error when running the command "collecTRI <- decoupleR::get_collectri(organism='human', split_complexes=FALSE)":

``` r
collecTRI <- decoupleR::get_collectri(organism='human', split_complexes=FALSE)
#> [1] TRUE
#> Error in do.call(stop, list(m), envir = env): `only_from` can be called only on data frames with `evidences` column.
```

<sup>Created on 2024-07-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

The error occurred when I’m following the tutorial on "Transcription factor activity inference in bulk RNA-seq".
I am using OmnipathR version 3.13.5 and decoupleR 2.9.7.

How can I fix this problem? Look forward to your reply. Thanks a lot!

**Comment by deeenes** [comment]
Hi @Megan0921, Since apparently the issue was an old cache item, I recommend you to wipe your cache, so the error never happens again. To do so, run in a new R session:

```
library(OmnipathR)
omnipath_cache_wipe()
```

**Comment by Megan0921** [comment]
Yes, that worked. Thanks a lot!@deeenes
