### ISSUE TITLE
NA handling by normalised_mean

### ISSUE THREAD

**Issue by adugourd** [saezlab/decoupleR#23]
Need the mean function to have na.rm = T

Else if the input expression matrix is incomplete, normalised means will almost always be 0. 

```r
map_dfr(seq_len(times), ~mean_run(random = TRUE)) %>% group_by(.data$tf, 
    .data$condition) %>% summarise(null_distribution = list(.data$value), 
    null_mean = mean(.data$value), null_sd = stats::sd(.data$value), 
    .groups = "drop") %>% left_join(y = mean_run(random = FALSE)
```

**Comment by jvelezmagic** [comment]
A direct `na.rm` argument could be passed to the `base::mean()` and` stats::sd()` functions to apply what you mention. Besides, I was thinking about the possibility of replacing the NAs in the matrix with zeros, so that their product don't contribute to the result, what do you think?

**Comment by jvelezmagic** [comment]
Closed due to no response.
