### ISSUE TITLE
Bug when using run_mean for kinase activity estimation.

### ISSUE THREAD

**Issue by adugourd** [saezlab/decoupleR#24]
Got this error when trying to use run_mean with phospho data for kinase activity estimation:

Can't convert <double> to <list>.

Here is the tracback. If you need I can provide the input object as well.
<error/vctrs_error_incompatible_type>
Can't convert <double> to <list>.
Backtrace:
     █
  1. ├─decoupleR::run_mean(...)
  2. │ └─`%>%`(...)
  3. ├─decoupleR::pivot_wider_profile(...)
  4. │ └─`%>%`(...)
  5. ├─tibble::column_to_rownames(., var = "id")
  6. │ ├─base::stopifnot(is.data.frame(.data))
  7. │ └─base::is.data.frame(.data)
  8. ├─dplyr::rename(...)
  9. ├─tidyr::pivot_wider(...)
 10. └─tidyr:::pivot_wider.data.frame(...)
 11.   └─tidyr::pivot_wider_spec(...)
 12.     └─vctrs::vec_cast(fill, val)
 13.       └─(function () ...
 14.         └─vctrs::vec_default_cast(...)
 15.           └─vctrs::stop_incompatible_cast(...)
 16.             └─vctrs::stop_incompatible_type(...)
 17.               └─vctrs:::stop_incompatible(...)
 18.                 └─vctrs:::stop_vctrs(...)

**Comment by adugourd** [comment]
The input matrix has NAs. If I use only complete cases then there is no error anymore. The problem comes likely from NAs, I would suspect regulons that have only NA values as measurements.

**Comment by jvelezmagic** [comment]
It is not clear to me how the NAs could cause the error. Please include a minimal reproducible example (AKA a reprex). If you've never heard of a reprex before, start by reading https://www.tidyverse.org/help/#reprex. c:

**Comment by jvelezmagic** [comment]
The error occurs due to a network with duplicate entries for each `tf-target` pair. Closed since it is not something inherent in the definition of the algorithm at the moment.
