### ISSUE TITLE
Can't reproduce SCIRA results

### ISSUE THREAD

**Issue by PauBadiaM** [saezlab/decoupleR#28]
Hi everyone,

While implementing SCIRA in python I discovered that the implementation of SCIRA in decoupleR is not exactly the same as in the original repo: https://github.com/WangNing0420/SCIRA. 
In their original implementation, see here https://github.com/WangNing0420/SCIRA/blob/master/R/sciraRegAct.R, before building any linear model they trim both gene expression and network by the intersection of genes. By doing this, the proportion of 0 in the final input changes and therefore the T values change too. In the current implementation of decoupleR there is no filtering before predicting the TF activities and therefore the results are not reproducible. Moreover, in the original code after trimming for the interestcion of genes they also center the expression data before predicting TF activities.
For the sake of reproducibility it would be good to add a `intersection = T` and `norm='c'` params.
Example original SCIRA
```r
library(SCIRA)
# Create toy regnet
regnet <- matrix(0,8,2)
regnet[,1] <- c(1,0,0,0,0,0,0,0)
regnet[,2] <- c(0,1,1,0,0,0,0,0)
colnames(regnet) <- c('tf1','tf2')
rownames(regnet) <- sprintf("g%s",seq(1:8))


# Create toy expr matrix
expr <- matrix(0,6,3)
expr[,1] <- c(1,2,3,4,5,6)
expr[,2] <- c(6,5,4,3,2,1)
expr[,3] <- c(1,1,0,1,1,1)
colnames(expr) <- c('s1','s2','s3')
rownames(expr) <- c('g1','g2','g4','g5','g7','g8')

# Compute TF activities
sciraRegAct(expr,regnet=regnet,norm="c",ncores=1)
```
Output:
```
            s1        s2        s3
tf1 -1.8240186 1.6329932 0.4082483
tf2 -0.8994896 0.8058384 0.4082483
```
Same but now with decoupleR:
```r
library(decoupleR)
# Create toy regnet
regnet <- dplyr::tibble(
    'tf'=c(rep('tf1', 8), rep('tf2', 8)),
    'target'=c(sprintf("g%s",seq(1:8)), sprintf("g%s",seq(1:8))),
    'mor'=c(1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0)
)

# Create toy expr matrix
expr <- matrix(0,6,3)
expr[,1] <- c(1,2,3,4,5,6)
expr[,2] <- c(6,5,4,3,2,1)
expr[,3] <- c(1,1,0,1,1,1)
colnames(expr) <- c('s1','s2','s3')
rownames(expr) <- c('g1','g2','g4','g5','g7','g8')

# Compute TF activities
tidyr::pivot_wider(decoupleR::run_scira(expr, regnet)[c('tf','condition','score')], id_cols=tf, names_from=condition, values_from=score)

```
Output:
```
  tf        s1    s2    s3
  <chr>  <dbl> <dbl> <dbl>
1 tf1   -1.73  1.73  0.408
2 tf2   -0.854 0.854 0.408
```

As you can see, results are slightly different. Despite this, when I was implementing Dorothea into python and I was using decouleR implementation I could not reproduce the cell clustering based on TF activities correctly, so it might be relevant.

**Comment by jvelezmagic** [comment]
Thank you for sharing this! I will check it out! c:
