### ISSUE TITLE
Error: Column `likelihood` not found in `.data`

### ISSUE THREAD

**Issue by linanzhang** [saezlab/decoupleR#31]
I loaded the regulon network from the [dorothea package](https://github.com/saezlab/dorothea/blob/master/vignettes/single_cell_vignette.Rmd):

```
## We read Dorothea Regulons for Human
dorothea_regulon_human = get(data("dorothea_hs", package = "dorothea"))
## We obtain the regulons based on interactions with confidence level A, B and C
regulon = dorothea_regulon_human %>% dplyr::filter(confidence %in% c("A","B","C"))
```

but `regulon` does not have the column `likelihood`. How to get the desired input network of `decoupleR`?

**Comment by jvelezmagic** [comment]
Hi, @linanzhang! Sorry for the late response.

- One way to solve your problem could include adding a new column full of 1s called `likelihood` into your `network`.
- On the other hand, `decoupleR` has its own built-in solution. Just pass a new parameter called `.likelihood = NULL`.

Let me know if I can help you with something else! 😋
