### ISSUE TITLE
Manuscript link broken

### ISSUE THREAD

**Issue by Skourtis** [saezlab/decoupleR#35]
Hi Just looking to read the manuscript for decoupleR. Thanks

**Comment by PauBadiaM** [comment]
Hi @Skourtis, 

Sorry for the delay! We were cleaning it up and making it ready for publication.  
Now it is available in bioRxiv: https://www.biorxiv.org/content/10.1101/2021.11.04.467271v1
And also the repository to reproduce the results: https://github.com/saezlab/decoupleR_manuscript
