### ISSUE TITLE
Duplicated regulons in mlm after filtering

### ISSUE THREAD

**Issue by smuellerd** [saezlab/decoupleR#47]
I get an error using mlm:
```
Error: Problem with `mutate()` column `model`.
ℹ `model = list(mlm_evaluate_model(.data$condition))`.
x Tibble columns must have compatible sizes.
* Size 159: Existing data.
* Size 162: Column `source`.
ℹ Only values of size one are recycled.
ℹ The error occurred in row 1.
```

Apparently some coefficients are getting removed, creating a mismatch. I suspect this might be caused by some TFs having the same target genes. It would be good to add a warning or an error. Thanks!

**Comment by PauBadiaM** [comment]
Hi @smuellerd,

I added an error whenever sources have the exact same targets in mlm, thanks!
