### ISSUE TITLE
Run_viper error 

### ISSUE THREAD

**Issue by Chengwei94** [saezlab/decoupleR#52]
This manage to run for run_wmean but run_viper encountered error

acts <- run_viper(  mat = mat, network = net, .source = "source", .target = "target",
   .mor = "mor", minsize = 5, method = "scale",  eset.filter = FALSE, cores = 1, 
   verbose = T)

Computing the association scores
Computing regulons enrichment with aREA
  |=======================================================================================================================| 100%
Computing pleiotropy for 1497 samples.

Process started at Thu Apr 14 15:43:54 2022
  |                                                                                                                       |   0%Error in if (tmp == 0) tmp <- 1 : missing value where TRUE/FALSE needed
In addition: Warning message:
In max(s1) : no non-missing arguments to max; returning -Inf`

**Comment by PauBadiaM** [comment]
Hi @Chengwei94 ,

Sorry but from this snipped of code and error message I cannot understand what might be wrong. Could you create a small reproducible example so that I can debug it? By the way, just in case try to run it without the argument `method`.
