### ISSUE TITLE
Vignette build fails due to missing packages

### ISSUE THREAD

**Issue by deeenes** [saezlab/decoupleR#54]
At least these packages are missing for a successful vignette build: magick, rsvg, GSVA. Should these be in the Suggests section?

**Comment by PauBadiaM** [comment]
Hi @deeenes 

Which version of decoupleR are you using? I do not use magick nor rsvg (I don't even have them installed in the enviroment where I test decoupleR). GSVA is already included in Suggests.

**Comment by deeenes** [comment]
Sorry, it was my mistake, now I install the dependencies properly: https://status.omnipathdb.org/decoupler/bioc-3.15/2022-04-21/install_deps.out
