### ISSUE TITLE
Issues retrieving data from PROGENy using decoupleR & OmintpathR

### ISSUE THREAD

**Issue by Vicbcn2001** [saezlab/decoupleR#61]
Hi,

Just running this instruction:

net <- get_progeny(organism = 'human', top = 100)

is giving this output:

Error in open.connection(con, "rb") : HTTP error 500.

It does in R4.1.0 and R4.2.1. This instruction previously ran fine with the same code. In addition, there is no issue to retrieve the data from dorothea within the same R session with this instruction:

net <- get_dorothea(organism='human', levels=c('A', 'B', 'C'))

Maybe it is a problem in the server specific for the PROGENy dataset.

Thank you
Best,

Vicente

**Comment by PauBadiaM** [comment]
Hi @Vicbcn2001,

Thanks for submitting an issue. Apparently we are having some problems with the OmniPath server currently. @deeenes could you take a look?

**Comment by deeenes** [comment]
Hi,

It was a transient server issue, sorrry about that, should be fine now.

Denes

**Comment by Vicbcn2001** [comment]
Hi,

I just checked the command and it is working fine. Thank you for your support and congratulations for the creation of these great resources! 

Vicente
