### ISSUE TITLE
GSVA error

### ISSUE THREAD

**Issue by tonyjhlam** [saezlab/decoupleR#62]
Getting the following error when running run_gsva()

`run_gsva(as.data.frame(expression), network = dre, method='gsva')`

unable to find an inherited method for function ‘gsva’ for signature ‘"data.frame", "list"’

**Comment by PauBadiaM** [comment]
Hi @tonyjhlam,

Thanks for checking out the package! Unfortunately decoupleR only accepts matrices as inputs, not data-frames. Whenever I have time I'll write a function that checks for this. Try it with a named matrix (with gene and sample or contrast names) and let me know please. Hope this was helpful.

**Comment by tonyjhlam** [comment]
Thanks @PauBadiaM this seems to have solved the issue.
