### ISSUE TITLE
Equivalent variable of t-value from limma in Deseq2 generated DEGs results

### ISSUE THREAD

**Issue by Diennguyen8290** [saezlab/decoupleR#70]
Hi,

Many thanks for the cool tool.

Please may I ask whether we can use DEGs results from DESeq2 pipeline as the input for Activity inference with Weighted Mean?

[contrast_acts <- run_wmean(mat=deg, net=net, .source='source', .target='target', .mor='weight', times = 100, minsize = 5)]

I was wondering if stat value of Deseq2 generated DEGs results can be used for that purpose.

Thank you.

Kind regards,
Dien

**Comment by PauBadiaM** [comment]
Hi @Diennguyen8290,

Thanks for the kind words! Yes, the stat value of Deseq2 can be used for enrichment

Cheers!

**Comment by Diennguyen8290** [comment]
Fab, many thanks @PauBadiaM
