### ISSUE TITLE
mutate error when downloading dorothea

### ISSUE THREAD

**Issue by roskcl** [saezlab/decoupleR#72]
Hello,

I am trying to download the dorothea database on R 4.2.2 but I am getting the following error. Could you please let me know how I can solve it? It was working before.

Thank you very much!

Best.

> net <- get_dorothea(organism='mouse', levels=c('A', 'B', 'C'))
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep
Run `rlang::last_error()` to see where the error occurred.

> rlang::last_error()
<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
---
Backtrace:
  1. decoupleR::get_dorothea(...)
 39. purrr (local) `<fn>`(`<rlb_rr__>`)
 40. cli::cli_abort(...)
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep
---
Backtrace:
  1. decoupleR::get_dorothea(...)
 27. purrr::map(., method, ...)
 28. purrr:::map_("list", .x, .f, ..., .progress = .progress)
 32. dplyr (local) .f(.x[[i]], ...)
Run `rlang::last_trace()` to see the full context.

> rlang::last_trace()
<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
---
Backtrace:
     ▆
  1. ├─decoupleR::get_dorothea(...)
  2. │ ├─... %>% ...
  3. │ └─OmnipathR::import_dorothea_interactions(...)
  4. │   └─OmnipathR:::import_omnipath(...)
  5. │     └─result %<>% count_references
  6. ├─dplyr::select(...)
  7. ├─dplyr::mutate(...)
  8. ├─dplyr::mutate(...)
  9. ├─dplyr::mutate(...)
 10. ├─dplyr::distinct(...)
 11. ├─dplyr::select(...)
 12. ├─OmnipathR:::count_references(.)
 13. │ └─data %>% ...
 14. ├─dplyr::mutate(...)
 15. ├─dplyr:::mutate.data.frame(...)
 16. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 17. │   ├─base::withCallingHandlers(...)
 18. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 19. │     └─mask$eval_all_mutate(quo)
 20. │       └─dplyr (local) eval()
 21. ├─base::ifelse(...)
 22. ├─OmnipathR:::strip_resource_labels(., inplace = FALSE, method = n_distinct)
 23. │ └─OmnipathR:::split_unique_join(...)
 24. │   └─OmnipathR:::split_apply(x = x, method = method, sep = sep, outsep = outsep)
 25. │     └─x %>% strsplit(sep) %>% map(method, ...) %>% unlist()
 26. ├─base::unlist(.)
 27. ├─purrr::map(., method, ...)
 28. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
 29. │   ├─purrr:::with_indexed_errors(...)
 30. │   │ └─base::withCallingHandlers(...)
 31. │   ├─purrr:::call_with_cleanup(...)
 32. │   └─dplyr (local) .f(.x[[i]], ...)
 33. │     └─rlang::check_dots_unnamed()
 34. │       └─rlang:::action_dots(...)
 35. │         ├─base (local) try_dots(...)
 36. │         └─rlang (local) action(...)
 37. │           └─rlang:::signal_abort(cnd, .file)
 38. │             └─base::signalCondition(cnd)
 39. ├─purrr (local) `<fn>`(`<rlb_rr__>`)
 40. │ └─cli::cli_abort(...)
 41. │   └─rlang::abort(...)
 42. │     └─rlang:::signal_abort(cnd, .file)
 43. │       └─base::signalCondition(cnd)
 44. └─dplyr (local) `<fn>`(`<prrr_rr_>`)
 45.   └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep
---
Backtrace:
     ▆
  1. ├─decoupleR::get_dorothea(...)
  2. │ ├─... %>% ...
  3. │ └─OmnipathR::import_dorothea_interactions(...)
  4. │   └─OmnipathR:::import_omnipath(...)
  5. │     └─result %<>% count_references
  6. ├─dplyr::select(...)
  7. ├─dplyr::mutate(...)
  8. ├─dplyr::mutate(...)
  9. ├─dplyr::mutate(...)
 10. ├─dplyr::distinct(...)
 11. ├─dplyr::select(...)
 12. ├─OmnipathR:::count_references(.)
 13. │ └─data %>% ...
 14. ├─dplyr::mutate(...)
 15. ├─dplyr:::mutate.data.frame(...)
 16. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 17. │   ├─base::withCallingHandlers(...)
 18. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 19. │     └─mask$eval_all_mutate(quo)
 20. │       └─dplyr (local) eval()
 21. ├─base::ifelse(...)
 22. ├─OmnipathR:::strip_resource_labels(., inplace = FALSE, method = n_distinct)
 23. │ └─OmnipathR:::split_unique_join(...)
 24. │   └─OmnipathR:::split_apply(x = x, method = method, sep = sep, outsep = outsep)
 25. │     └─x %>% strsplit(sep) %>% map(method, ...) %>% unlist()
 26. ├─base::unlist(.)
 27. └─purrr::map(., method, ...)
 28.   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
 29.     ├─purrr:::with_indexed_errors(...)
 30.     │ └─base::withCallingHandlers(...)
 31.     ├─purrr:::call_with_cleanup(...)
 32.     └─dplyr (local) .f(.x[[i]], ...)
 33.       └─rlang::check_dots_unnamed()
 34.         └─rlang:::action_dots(...)
 35.           ├─base (local) try_dots(...)
 36.           └─rlang (local) action(...)

**Comment by PauBadiaM** [comment]
Hi @roskcl 

It looks like there is an issue coming from OmniPath, could you install its latest version from GitHub and try again?
```
remotes::install_github("saezlab/OmnipathR")
```

**Comment by roskcl** [comment]
Yes! That solved the issue, thanks! :)
