### ISSUE TITLE
Differences between two ways of getting dorothea database

### ISSUE THREAD

**Issue by yunbokai** [saezlab/decoupleR#76]
Hi,
    It seems that I have two ways to get  dorothea database. However, the result is different.
First:
`data(dorothea_hs, package = "dorothea")
network <- dorothea_hs
confidence_lbls = c("A","B","C")
network  = network  %>% dplyr::filter(confidence %in% confidence_lbls)`
Second:
`network <- get_dorothea(organism='human', levels=c('A', 'B', 'C'))`
Could you please explain the differences for me? The second way have more TFs. So is it the newest database?
Thanks!

**Comment by PauBadiaM** [comment]
Hi @yunbokai 

Thanks for checking out the package. Yes, this is because there are two versions, as discussed in #68 . We recommend using the one in ``decoupleR::get_dorothea`` as its the latest version.
