### ISSUE TITLE
How to understand the `weight` and `p_value` in the result of get_progeny.

### ISSUE THREAD

**Issue by xiangpin** [saezlab/decoupleR#84]
Hello
Thanks for developing the packages. I used it to infer the pathway activity in my data. But I don't understand the 
`weight` and `p_value` in the result of `get_progeny` from [PROGENy](https://saezlab.github.io/progeny/). 

+ What do the negative `weight` and positive `weight` values mean respectively?

+ What does the `p_value` mean? Can we select the targets based on the `p_value`?

**Comment by PauBadiaM** [comment]
Hi @xiangpin 

The weights indicate how each gene is associated to a given pathway. A positive Pathway-Gene weight indicates that that gene was seen to be upregulated in stimulation experiments for that pathway. A negative weight indicates that that gene was seen to be downregulated when that pathway was stimulated. The p-value tells how confident are we about these weights. You can find the exact protocol on how the weights and p-values where extracted from a collection of stimulation experiments in the original publication of progeny: https://doi.org/10.1038/s41467-017-02391-6.
Regarding the p-values, we use them to rank Pathway-Gene interactions and then we select the top N, N being an arbitrary integer number (which corresponds to the `top` argument of the `get_progeny` function). The smaller N is, the more confident we are that those genes are associated to a given pathway but we have low coverage, with bigger N we have the opposite effect, larger coverage but less confidence.
Hope this was helpful!
