### ISSUE TITLE
how to compute the pathway activity score for the pathway if I do not have the pathway genes weight 

### ISSUE THREAD

**Issue by FADHLyemen** [saezlab/decoupleR#92]
Hi
I am interested in computing PAS for the pathway activity score for the mtor from the Reactome database. I have 39 genes annotated under this pathway. unfortunately, decoubler needs weights weight for these genes which I do not know how to get them.
any help?
second, did you compare the performance of MLM with ssGSEA? 
Thank you

**Comment by deeenes** [comment]
Hi, The pathway activity inference is based on transcriptomics signatures, which are available for canonical pathways in the [PROGENy database](https://saezlab.github.io/decoupleR/articles/pw_bk.html#progeny-model). For Reactome pathways no such signatures exist, hence it's not possible to infer their activities.

**Comment by FADHLyemen** [comment]
How did you infer the pathway genes weight? is it disease-specific? 
did you compare MLM with ssGSEA?
Regards

**Comment by deeenes** [comment]
The weights have been derived by fitting models on transcriptomics data from dozens of targeted perturbation experiments, [as described here](https://www.nature.com/articles/s41467-017-02391-6). They are not disease specific. The other question @PauBadiaM will answer bc I'm not familiar with the topic.

**Comment by PauBadiaM** [comment]
Hi @FADHLyemen,

You can use `ulm` or `mlm` without weights, just add a column called `mor` in your `net` dataframe with 1s, like this:
```R
net['mor'] <- 1
```

We did compare MLM and GSEA, and we found that any linear method (both `ulm` and `mlm`) outperforms classic enrichment analysis like ssGSEA (in this plot is `fgsea`) and GSVA (Fig 1C of the manuscript).
![](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformaticsadvances/2/1/10.1093_bioadv_vbac016/2/vbac016f1.jpeg?Expires=1698828184&Signature=mFzw9kXHOVzQYcTCao16-UaujMa6YMC1aMG1AwDhxOFimPqHiCyxBOAkzTsx74HuWWQOiBswFVeSnzd2t3gixLMyn2BabKjP5aWPSc0jKU6B0KztDXUSdvD28q5GcOMqdRRACPu-fnkYEIg3BtgzzIInMZ7G9SitVY4jB46yJydgo6EIHDyrm8tf6kdkQOyr4eqUuQovKqgFaq9KhV4XlSEN5HgSC2ihpKWAtChAIaZdGnQC8ypoAU9BnMw62lQucTdbeBJh5QThiaAVhEZWq-IqV7U6zdIXd2BrDfJDH1suGKGk8n~cUigN3H3m0~grVnmR3NAmhxqLK2j1vjDJ~A__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)
